name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.1

  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v2.0.1
      with:
        version: 4.2.2
        use-dotnet: false
    - name: Initialize Godot
      run: |
        godot --path . --headless --import
    - name: Run tests
      run: |
        godot --path . --headless --script addons/gut/gut_cmdln.gd -gjunit_xml_file=test-report.xml -gexit
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-report.xml
        comment_mode: failures
        test_file_prefix: "-res://"
